### ISSUE TITLE
？？？

### ISSUE THREAD

**Issue by yunzimos** [dtsdao/AliDDNS#4]
看的一脸懵逼

**Comment by dtsdao** [comment]
原贴在 [https://bbs.aliyun.com/read/289624.html](https://bbs.aliyun.com/read/289624.html) ，把需要填的填好就行，AccessKey可以在阿里云控制台看到
我已经不再维护本软件，更多的功能可以使用这个人维护的: [https://github.com/wisdomwei201804/AliDDNS](https://github.com/wisdomwei201804/AliDDNS)
